services:
  personal-website:
    image: personal-website:latest
    container_name: personal-website
    ports:
      - "55001:55001"
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"